spring.application.name=metadata-service
# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/vflowdb
spring.datasource.username=vflowuser
spring.datasource.password=vflowpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ Settings
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest